name: Backend CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run backend server
        run: |
          cd backend
          flask db upgrade
          flask run &
          sleep 5 # Give the server time to start
        working-directory: ${{ github.workspace }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Test API with curl
        run: |
          set -e
          echo "--- Sign up ---"
          curl -X POST -H "Content-Type: application/json" -d '{"name":"testuser","email":"test@example.com","password":"password"}' http://127.0.0.1:5000/api/auth/signup
          echo "\n\n--- Log in ---"
          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d '{"email":"test@example.com","password":"password"}' http://127.0.0.1:5000/api/auth/login | jq -r .access_token)
          if [ -z "$TOKEN" ]; then
            echo "Failed to get token"
            exit 1
          fi
          echo "Token: $TOKEN"

          echo "\n\n--- Create Group ---"
          GROUP_RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"name":"Test Group","participant_ids":[]}' http://127.0.0.1:5000/api/groups)
          GROUP_ID=$(echo $GROUP_RESPONSE | jq -r .group_id)
          if [ -z "$GROUP_ID" ]; then
            echo "Failed to create group"
            echo "Response: $GROUP_RESPONSE"
            exit 1
          fi
          echo "Group ID: $GROUP_ID"

          echo "\n\n--- Get Groups ---"
          curl -X GET -H "Authorization: Bearer $TOKEN" http://127.0.0.1:5000/api/groups

          echo "\n\n--- Add Expense ---"
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"title":"Test Expense","amount":100.00}' http://127.0.0.1:5000/api/groups/$GROUP_ID/expenses

          echo "\n\n--- Get Expenses ---"
          curl -X GET -H "Authorization: Bearer $TOKEN" http://127.0.0.1:5000/api/groups/$GROUP_ID/expenses